[user]
name = "Daan van der Kallen"
email = "mail@daanvdk.com"

[ui]
default-command = "log"
diff-editor = "jjdiff"
diff-instructions = false
diff-formatter = ["jjdiff", "--print", "$left", "$right"]
 
[git]
private-commits = "description(glob:'private:*')"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_nonempty(@)"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"closest_nonempty(to)" = "heads(::to ~ empty())"
