[user]
name = "Daan van der Kallen"
email = "mail@daanvdk.com"

[ui]
default-command = "log"
diff-editor = "jjdiff"
diff-instructions = false
diff-formatter = ["jjdiff", "--print", "$left", "$right"]
 
[git]
private-commits = "description(glob:'private:*')"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_nonempty(@)"]
push = ["git", "push"]
push-new = ["git", "push", "--change", "closest_nonempty(@)"]
push-all = ["git", "push", "--all"]
fetch = ["git", "fetch"]
rebase-all = ["rebase", "-s", "roots(trunk()..mutable() ~ trunk()::)", "-d", "trunk()"]
log-trunk = ["log", "-r", "ancestors(trunk(), 10)"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"closest_nonempty(to)" = "heads(::to ~ empty())"
