format = "$directory$character"
right_format = "$git_branch$git_metrics"
add_newline = false

[character]
success_symbol = "[»](white)"
error_symbol = "[»](white)"
vicmd_symbol = "[ VI ](black bold bg:green)[](green)"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "blue bold"

[git_branch]
format = "[$symbol$branch]($style)"
style = "yellow bold"
