format = '$directory$character'
right_format = '$git_branch$git_metrics'
add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = false
style = "blue bold"

[character]
success_symbol = '[»](white)'
error_symbol = '[»](red)'
vicmd_symbol = '[»](white)'

[git_branch]
format = '[$symbol$branch]($style)'
style = "yellow bold"
